[env:esp32-c6-devkitc-1]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-c6-devkitc-1

framework = arduino

monitor_speed = 115200
upload_speed = 460800

board_build.flash_mode = dio
board_build.flash_size = 4MB

build_flags =
    -D USER_SETUP_LOADED=1
    -include $PROJECT_DIR/include/tft_setup.h

lib_deps =
    bodmer/TFT_eSPI@^2.5.43
    adafruit/Adafruit MPU6050@^2.2.9
    adafruit/Adafruit Unified Sensor@^1.1.15
    adafruit/Adafruit AHTX0@^2.0.6
    arduino-libraries/NTPClient@^3.2.1
    h2zero/NimBLE-Arduino@^2.5.1
